project_name: notification_relay
before:
  hooks:
    - go mod tidy
    - cp ../LICENSE .
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    binary: notification_relay
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    image_templates:
      - "ghcr.io/cyb3r-jak3/notification_relay:latest"
      - "ghcr.io/cyb3r-jak3/notification_relay:{{ .Tag }}"
      - "ghcr.io/cyb3r-jak3/notification_relay:v{{ .Major }}"
      - "cyb3rjak3/notification_relay:latest"
      - "cyb3rjak3/notification_relay:{{ .Tag }}"
      - "cyb3rjak3/notification_relay:v{{ .Major }}"
    goarch: amd64
    dockerfile: ../release.Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/Cyb3r-Jak3/notification_relay"

  -
    image_templates:
      - "cyb3rjak3/notification_relay:latest-arm64v8"
      - "cyb3rjak3/notification_relay:{{ .Tag }}-arm64v8"
      - "cyb3rjak3/notification_relay:v{{ .Major }}-arm64v8"
      - "ghcr.io/cyb3r-jak3/notification_relay:latest-arm64v8"
      - "ghcr.io/cyb3r-jak3/notification_relay:{{ .Tag }}-arm64v8"
      - "ghcr.io/cyb3r-jak3/notification_relay:v{{ .Major }}-arm64v8"
    goarch: arm64
    dockerfile: ../release.Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/Cyb3r-Jak3/notification_relay"


signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

release:
  draft: true