name: Test Go

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
    paths:
      - '**.go'
      - .github/workflows/go.yml
      - "go.mod"
      - "go.sum"


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: actions/cache@v3.0.2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Extra
        run: |
          go get -u github.com/securego/gosec/v2/cmd/gosec@latest
          go get ./...


#      Ignoring until I write tests
#      - name: Test
#        run: make test

      - name: Gosec Security Scanner
        run: make scan

      - name: GoSec Report
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: security.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: security.sarif
